# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91076b199fb8bcbe59cd7c776f2907e59a06a74ed1772b9c0e4fc800f409b97307d46ad7ccac2422db696e6af57730706e4bce3dd8567fb83355728766bd2463

test:
  secret_key_base: 41597433a91369463f18df8beb053e772472325b362b72d77d061e4a5dc758b210942d57f8829178f5069a33e9c9f23f2a53516c0556a43bb447f7fc17c94e0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
